services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: srs_analyst
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d srs_analyst"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
<<<<<<< HEAD
      build: ./backend
      container_name: fastapi_app
      ports:
        - "8000:8000"
      environment:
        - DATABASE_URL=postgresql://postgres:${DATABASE_PASSWORD}@postgres_db:5432/srs_analyst
      depends_on:
        db:
          condition: service_healthy


=======
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      # هنا السر! نقوم بتغيير localhost إلى اسم الخدمة db
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/srs_analyst
    depends_on:
      - db
>>>>>>> c4bd56f (configuring the docker fastapi container)
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend